# Generated by Django 2.0.2 on 2018-03-03 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='command',
            new_name='comment',
        ),
    ]
