# Generated by Django 2.0.2 on 2018-03-03 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180303_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='error_date',
            new_name='error_rate',
        ),
    ]
