# Generated by Django 2.0.2 on 2018-03-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180303_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='labeled_data',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='unlabeled_data',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
