# Generated by Django 2.0.2 on 2018-03-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180304_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='labeled_data',
            field=models.FileField(upload_to='labeled_data'),
        ),
        migrations.AlterField(
            model_name='project',
            name='unlabeled_data',
            field=models.FileField(blank=True, upload_to='unlabeled_data'),
        ),
    ]
