# Generated by Django 2.0.2 on 2018-03-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_attribute_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='unlabeled_data',
            field=models.CharField(max_length=500),
        ),
    ]
