# Generated by Django 2.0.2 on 2018-03-07 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20180306_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='type',
            new_name='predict_type',
        ),
    ]
