# Generated by Django 2.0.2 on 2018-04-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20180307_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='error_rate',
            new_name='accurate_rate',
        ),
        migrations.AddField(
            model_name='project',
            name='accurate_list',
            field=models.TextField(blank=True),
        ),
    ]
