# Generated by Django 2.0.2 on 2018-04-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20180405_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='attribute_num',
        ),
        migrations.AlterField(
            model_name='project',
            name='accurate_rate',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
