# Generated by Django 2.0.2 on 2018-04-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20180416_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mean_squared_error',
            field=models.TextField(blank=True),
        ),
    ]
