# Generated by Django 2.0.2 on 2018-04-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_mean_squared_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='mean_squared_error',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
