# Generated by Django 2.0.2 on 2018-04-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20180416_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='attribute_num',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
