# Generated by Django 2.0.2 on 2018-04-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_project_attribute_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='attribute_num',
            field=models.IntegerField(blank=True),
        ),
    ]
