# Generated by Django 2.0.2 on 2018-04-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20180422_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='attribute_num',
            field=models.IntegerField(null=True),
        ),
    ]
