# Generated by Django 2.0.2 on 2018-04-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20180422_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='algorithm_selected',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
