# Generated by Django 2.0.2 on 2018-04-23 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20180422_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='training_result',
            new_name='predict_result',
        ),
    ]
